version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_DATABASE: 'classchat'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'changeme'
  app:
    build: .
    environment:
      WAIT_HOSTS: mysql:3306
      DB_USERNAME: 'user'
      DB_PASSWORD: 'changeme'
    volumes:
      - './:/root'
    ports:
      - '8080:8000'
  websockets:
    build:
      context: .
      dockerfile: websockets.Dockerfile
    environment:
      WAIT_HOSTS: mysql:3306
      DB_USERNAME: 'user'
      DB_PASSWORD: 'changeme'
    ports:
      - '8001:8001'